on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 10

      - run: pnpm build
        env:
          NEXT_PUBLIC_BASE_PATH: "/${{ github.event.repository.name }}"

      - uses: peaceiris/actions-gh-pages@v3
        env:
          NEXT_PUBLIC_CANONICAL_URL: ${{ secrets.NEXT_PUBLIC_CANONICAL_URL }}
          NEXT_PUBLIC_DEPLOYMENT_URL: ${{ secrets.NEXT_PUBLIC_DEPLOYMENT_URL }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          force_orphan: true
